nginx:
  build: ./NGINX
  links:
    - server1:server1
    - server2:server2
    - server3:server3
  ports:
    - "80:80"
server1:
  build: ./node
  links:
    - redis
  ports:
    - "3000"
server2:
  build: ./node
  links:
    - redis
  ports:
    - "3000"
server3:
  build: ./node
  links:
    - redis
  ports:
    - "3000"
redis:
  image: redis
  container_name: cache
  ports:
    - "6379"
