CREATE DATABASE IF NOT EXISTS airbnb;

USE airbnb;

DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS listings;

CREATE TABLE IF NOT EXISTS listings (
  id INT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS reviews (
  id VARCHAR(60) NOT NULL,
  listing_id INT NOT NULL,
  author VARCHAR(60) NOT NULL,
  user_id VARCHAR(60) NOT NULL,
  avatar_url VARCHAR(255),
  date DATE,
  body TEXT NOT NULL,
  flagged BOOLEAN,
  PRIMARY KEY (id)
  -- FOREIGN KEY (listing_id)
  --   REFERENCES listings(id)
) ENGINE=InnoDB  DEFAULT CHARSET=UTF8MB4;